version: '3.7'
services:
  node-app:
    image: node:14-alpine
    container_name: node-app
    env_file:
      - .env
    environment: 
      - NODE_ENV=production
    build:
      context: ./
    networks:
      - proxy-tier
      - caddy

  caddy:
    image: caddy/caddy:2.2.1-alpine
    networks:
      - proxy-tier
      - caddy 
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

networks:
  proxy-tier:
    external:
      name: caddy-proxy
  caddy:     

volumes:
  caddy_data:
  caddy_config:  